/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicaRouteImport } from './routes/clinica'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EquipeIndexRouteImport } from './routes/equipe.index'
import { Route as EquipeSlugRouteImport } from './routes/equipe.$slug'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaRoute = ClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/equipe/$slug',
  path: '/equipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/localizacao': typeof LocalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/localizacao': typeof LocalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/equipe': typeof EquipeIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/localizacao': typeof LocalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinica'
    | '/contato'
    | '/faq'
    | '/localizacao'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/equipe/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinica'
    | '/contato'
    | '/faq'
    | '/localizacao'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/servicos/$slug'
    | '/blog'
    | '/equipe'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/clinica'
    | '/contato'
    | '/faq'
    | '/localizacao'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/equipe/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/equipe/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicaRoute: typeof ClinicaRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EquipeSlugRoute: typeof EquipeSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica': {
      id: '/clinica'
      path: '/clinica'
      fullPath: '/clinica'
      preLoaderRoute: typeof ClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/equipe/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicaRoute: ClinicaRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  EquipeSlugRoute: EquipeSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EquipeIndexRoute: EquipeIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
